name: Code Quality

on:
  pull_request:
    branches:
      - development

env:
  NODE_VERSION: 16

jobs:
  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log
        run: |
          echo '${{ toJSON(github) }}'

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format

      - name: Run Linting
        run: npm run lint
      
      - name: Run Unit Tests
        run: npm test

      - name: Run Build
        run: npm run build
      