name: Code Quality

on:
  pull_request:
    branches:
      - development

env:
  NODE_VERSION: 16

jobs:
  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Check
        run: |
          npm run format
          npm run lint
          npm run lint:types
          npm run test:ci
          npm run build

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      