on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  NODE_VERSION: 16

jobs:
  release:
    if: github.event.pull_request.merged && contains(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        registry-url: https://registry.npmjs.org/
        node-version: ${{env.NODE_VERSION}}

    - name: Checkout Repo and Default Branch
      uses: actions/checkout@v3
      with:
        token: ${{secrets.CI_TOKEN}}

    - name: setup git config
      run: |
        git config user.name "Github Action bot"
        git config user.email "<>"

    - name: Pull Changes
      run: git pull

    - name: Install Dependencies
      run: npm ci

    - name: Check
      run: |
        npm run format
        npm run lint
        npm run lint:types
        npm test
        npm run build

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.CI_TOKEN }}

    - name: Bump Lib Version (patch)
      if: github.head_ref == 'release/patch'
      run: npm version patch
    - name: Bump Lib Version (minor)
      if: github.head_ref == 'release/minor'
      run: npm version minor
    - name: Bump Lib Version (major)
      if: github.head_ref == 'release/major'
      run: npm version major

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

    - name: Push branch & tag
      run: | 
        git push
        git push --tags
    