on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  NODE_VERSION: 16

jobs:
  release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        registry-url: https://registry.npmjs.org/
        node-version: ${{env.NODE_VERSION}}

    - name: Checkout Repo and Default Branch
      uses: actions/checkout@v3

    - name: setup git config
      run: |
        git config user.name "${{secrets.F_PUSH_NAME}}"
        git config user.email "${{secrets.F_PUSH_EMAIL}}"

    - name: Pull Changes
      run: git pull

    - name: Install Dependencies
      run: npm ci

    - name: Check
      run: |
        npm run format
        npm run lint
        npm test
        npm run build

    - name: Bump Lib Version
      run: npm version patch

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

    - name: Push branch & tag
      run: | 
        git push --force
        git push --tags
    