name: Update Coverage
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: npm test

    - name: Create Coverage Badge
      uses: jpb06/jest-badges-action@latest
      with:
        branches: development,main