name: Update Coverage
on:
  push:
    branches: [development]

env:
  NODE_VERSION: 16

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

      - name: Create Coverage Badge
        run: npm run create-badge
      
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'development'