name: Update Coverage
on:
  pull_request:
    branches: [main, development]
    types:
      - closed

env:
  NODE_VERSION: 16

jobs:
  bump:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

      - name: Create Coverage Badge
        uses: jpb06/jest-badges-action@latest